export const advanceSolutionData = [
    {
      id: 1,
      cardBGImage: '/intelligent-tech/cards-background/bg-card-machine-learning.png',
      cardBGColor: '#EFE9FB',
      cardTitle: "Machine Learning",
      cardIconUrl: '/intelligent-tech/icons/machineLearning.svg',
      cardHeading: 'Automated Pattern Recognition',
      cardDesc: 'Our ability in constructing, training, and deploying ML models assures an effective implementation process',
      isArrow: false,
    },
    {
      id: 2,
      cardBGImage: '/intelligent-tech/cards-background/bg-card-artificial-intelligence.png',
      cardBGColor: '#EFE9FB',
      cardTitle: "Artificial Intelligence",
      cardIconUrl: '/intelligent-tech/icons/artificialIntelligence.svg',
      cardHeading: 'Cognitive Computing Solutions',
      cardDesc: 'Ensure improvement in customer experiences, facilitating acceleration and optimized business operations.',
      isArrow: false,
    },
    {
      id: 3,
      cardBGImage: '/intelligent-tech/cards-background/bg-card-rpa.png',
      cardBGColor: '#EFE9FB',
      cardTitle: "Robotic Process Automation",
      cardIconUrl: '/intelligent-tech/icons/roboticProcessAutomation.svg',
      cardHeading: 'Efficient Task Automation',
      cardDesc: 'Minimize time-consuming repetitive tasks and dedicate more time to strategic initiatives',
      isArrow: false,
    },
    {
      id: 4,
      cardBGImage: '/intelligent-tech/cards-background/bg-card-asset-management.png',
      cardBGColor: '#EFE9FB',
      cardTitle: "IIoT",
      cardIconUrl: '/intelligent-tech/icons/iIoT.svg',
      cardHeading: 'Asset Optimization and Uptime',
      cardDesc: 'Optimize industrial operations with real-time machine performance data and predictive maintenance insights from our IoT services.',
      isArrow: false,
    },
  ];
